package com.plantnfc.presentation

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Screen titles
    val generatorTitle: String,
    val readerTitle: String,
    val listTitle: String,
    val settingsTitle: String,

    // Generator – plant picker
    val plantSelection: String,
    val plant: String,
    val loadingDots: String,
    val variety: String,

    // Generator – data fields
    val nfcData: String,
    val nfcId: String,
    val latinName: String,
    val dateHint: String,
    val nfcType: String,

    // Generator – GPS
    val gpsData: String,
    val on: String,
    val off: String,
    val startLiveTracking: String,
    val stopLockData: String,
    val latitude: String,
    val longitude: String,
    val altitude: String,
    val accuracy: String,
    val compressedPacket: String,

    // Generator – preview & actions
    val preview: String,
    val dataWillAppear: String,
    val linkWillAppear: String,
    val actions: String,
    val writeNfc: String,
    val waiting: String,
    val save: String,
    val saving: String,
    val copyNfc: String,
    val copyLink: String,

    // Reader
    val scan: String,
    val holdNfcTag: String,
    val clear: String,
    val noTagScanned: String,
    val link: String,
    val serial: String,
    val decodedFields: String,
    val fieldNfcId: String,
    val fieldPlantId: String,
    val fieldName: String,
    val fieldVariety: String,
    val fieldLatin: String,
    val fieldType: String,
    val fieldDate: String,
    val fieldNotes: String,
    val gps: String,

    // NFC list
    val noRecordsYet: String,
    val search: String,
    val syncedLabel: String,
    val pendingLabel: String,
    val conflictLabel: String,
    val delete: String,
    val deleteQuestion: String,
    val cancel: String,

    // Settings
    val language: String,
    val english: String,
    val hungarian: String,
    val googleSheets: String,
    val plantSheetIdLabel: String,
    val plantSheetNameLabel: String,
    val nfcWriterUrlLabel: String,
    val nfcWriterSecretLabel: String,
    val saveSettings: String,
    val settingsSaved: String,
    val reloadPlants: String,
    val resetDefaults: String,

    // NFC type labels
    val nfcTypePlant: String,
    val nfcTypeGraft: String,
    val nfcTypeSeed: String,

    // SnackMsg translations
    val msgNfcWriteSuccess: String,
    val msgNfcWriteErrorPrefix: String,
    val msgSaved: String,
    val msgSaveFailedPrefix: String,
    val msgSelectPlantFirst: String,
    val msgGenerateFirst: String,
    val msgTapNfcTag: String,
    val msgLocationPermRequired: String,
    val msgCopied: String,
    val msgSynced: String,
    val msgImported: String,

    // GpsStatus translations
    val gpsReady: String,
    val gpsFetching: String,
    val gpsUpdatingPrefix: String,   // e.g. "Updating… (±" then "{n}m)"
    val gpsLocked: String,
    val gpsNoFix: String,
    val gpsPermDenied: String,
)

fun AppStrings.localize(msg: SnackMsg): String = when (msg) {
    is SnackMsg.NfcWriteSuccess      -> msgNfcWriteSuccess
    is SnackMsg.NfcWriteError        -> "$msgNfcWriteErrorPrefix${msg.detail}"
    is SnackMsg.Saved                -> msgSaved
    is SnackMsg.SaveFailed           -> "$msgSaveFailedPrefix${msg.detail}"
    is SnackMsg.SelectPlantFirst     -> msgSelectPlantFirst
    is SnackMsg.GenerateFirst        -> msgGenerateFirst
    is SnackMsg.TapNfcTag            -> msgTapNfcTag
    is SnackMsg.LocationPermRequired -> msgLocationPermRequired
    is SnackMsg.Copied               -> msgCopied
    is SnackMsg.Synced               -> msgSynced
    is SnackMsg.Imported             -> msgImported
}

fun AppStrings.localize(status: GpsStatus): String = when (status) {
    is GpsStatus.Ready           -> gpsReady
    is GpsStatus.Fetching        -> gpsFetching
    is GpsStatus.Updating        -> "$gpsUpdatingPrefix${status.accuracyM}m)"
    is GpsStatus.Locked          -> gpsLocked
    is GpsStatus.NoFix           -> gpsNoFix
    is GpsStatus.PermissionDenied -> gpsPermDenied
}

// ── String sets ───────────────────────────────────────────────────────────────

val englishStrings = AppStrings(
    generatorTitle          = "🌱 NFC Generator",
    readerTitle             = "📖 NFC Reader",
    listTitle               = "📋 NFC Records",
    settingsTitle           = "⚙️ Settings",
    plantSelection          = "Plant Selection",
    plant                   = "Plant",
    loadingDots             = "Loading…",
    variety                 = "Variety",
    nfcData                 = "NFC Data",
    nfcId                   = "NFC ID",
    latinName               = "Latin Name",
    dateHint                = "Date (YYYY-MM-DD)",
    nfcType                 = "NFC Type",
    gpsData                 = "GPS Data",
    on                      = "On",
    off                     = "Off",
    startLiveTracking       = "Start Live Tracking",
    stopLockData            = "Stop & Lock Data",
    latitude                = "Latitude",
    longitude               = "Longitude",
    altitude                = "Altitude",
    accuracy                = "Accuracy",
    compressedPacket        = "Compressed Packet",
    preview                 = "Preview",
    dataWillAppear          = "Data will appear here…",
    linkWillAppear          = "Link will appear here…",
    actions                 = "Actions",
    writeNfc                = "Write NFC",
    waiting                 = "Waiting…",
    save                    = "Save",
    saving                  = "Saving…",
    copyNfc                 = "Copy NFC",
    copyLink                = "Copy Link",
    scan                    = "Scan",
    holdNfcTag              = "Hold an NFC plant tag near your phone to read it.",
    clear                   = "Clear",
    noTagScanned            = "No tag scanned yet…",
    link                    = "Link",
    serial                  = "Serial",
    decodedFields           = "Decoded Fields",
    fieldNfcId              = "NFC ID",
    fieldPlantId            = "Plant ID",
    fieldName               = "Name",
    fieldVariety            = "Variety",
    fieldLatin              = "Latin",
    fieldType               = "Type",
    fieldDate               = "Date",
    fieldNotes              = "Notes",
    gps                     = "GPS",
    noRecordsYet            = "No records yet",
    search                  = "Search…",
    syncedLabel             = "✓ synced",
    pendingLabel            = "↑ pending",
    conflictLabel           = "! conflict",
    delete                  = "Delete",
    deleteQuestion          = "Delete?",
    cancel                  = "Cancel",
    language                = "Language",
    english                 = "English",
    hungarian               = "Hungarian",
    googleSheets            = "Google Sheets",
    plantSheetIdLabel       = "Plant Data Sheet ID",
    plantSheetNameLabel     = "Plant Data Sheet Name",
    nfcWriterUrlLabel       = "NFC List Writer URL",
    nfcWriterSecretLabel    = "NFC List Writer Secret",
    saveSettings            = "Save Settings",
    settingsSaved           = "Settings saved ✓",
    reloadPlants            = "Reload Plant List",
    resetDefaults           = "Reset to defaults",
    nfcTypePlant            = "n – plant",
    nfcTypeGraft            = "o – graft",
    nfcTypeSeed             = "m – seed",
    msgNfcWriteSuccess      = "Written to NFC tag ✅",
    msgNfcWriteErrorPrefix  = "Write error: ",
    msgSaved                = "Saved!",
    msgSaveFailedPrefix     = "Save failed: ",
    msgSelectPlantFirst     = "Select a plant first",
    msgGenerateFirst        = "Generate NFC data first",
    msgTapNfcTag            = "Tap NFC tag to phone…",
    msgLocationPermRequired = "Location permission required for GPS",
    msgCopied               = "Copied!",
    msgSynced               = "Synced!",
    msgImported             = "Imported!",
    gpsReady                = "Ready.",
    gpsFetching             = "Fetching GPS satellites…",
    gpsUpdatingPrefix       = "Updating… (±",
    gpsLocked               = "Data Locked.",
    gpsNoFix                = "No fix yet.",
    gpsPermDenied           = "GPS permission denied",
)

val hungarianStrings = AppStrings(
    generatorTitle          = "🌱 NFC Generátor",
    readerTitle             = "📖 NFC Olvasó",
    listTitle               = "📋 NFC Rekordok",
    settingsTitle           = "⚙️ Beállítások",
    plantSelection          = "Növény kiválasztás",
    plant                   = "Növény",
    loadingDots             = "Betöltés…",
    variety                 = "Fajta",
    nfcData                 = "NFC Adatok",
    nfcId                   = "NFC ID",
    latinName               = "Latin Név",
    dateHint                = "Dátum (ÉÉÉÉ-HH-NN)",
    nfcType                 = "NFC Típus",
    gpsData                 = "GPS Adatok",
    on                      = "Be",
    off                     = "Ki",
    startLiveTracking       = "Élő követés indítása",
    stopLockData            = "Megállítás és rögzítés",
    latitude                = "Szélesség",
    longitude               = "Hosszúság",
    altitude                = "Magasság",
    accuracy                = "Pontosság",
    compressedPacket        = "Tömörített csomag",
    preview                 = "Előnézet",
    dataWillAppear          = "Az adatok itt jelennek meg…",
    linkWillAppear          = "A link itt jelenik meg…",
    actions                 = "Műveletek",
    writeNfc                = "NFC Írás",
    waiting                 = "Várakozás…",
    save                    = "Mentés",
    saving                  = "Mentés…",
    copyNfc                 = "NFC Másolása",
    copyLink                = "Link Másolása",
    scan                    = "Olvasás",
    holdNfcTag              = "Tartsd az NFC növény jelölőt a telefonhoz az olvasáshoz.",
    clear                   = "Törlés",
    noTagScanned            = "Még nem olvasott jelölő…",
    link                    = "Link",
    serial                  = "Sorozatszám",
    decodedFields           = "Dekódolt mezők",
    fieldNfcId              = "NFC ID",
    fieldPlantId            = "Növény ID",
    fieldName               = "Név",
    fieldVariety            = "Fajta",
    fieldLatin              = "Latin",
    fieldType               = "Típus",
    fieldDate               = "Dátum",
    fieldNotes              = "Megjegyzés",
    gps                     = "GPS",
    noRecordsYet            = "Még nincs rekord",
    search                  = "Keresés…",
    syncedLabel             = "✓ szinkronizálva",
    pendingLabel            = "↑ függőben",
    conflictLabel           = "! ütközés",
    delete                  = "Törlés",
    deleteQuestion          = "Törlés?",
    cancel                  = "Mégse",
    language                = "Nyelv",
    english                 = "Angol",
    hungarian               = "Magyar",
    googleSheets            = "Google Táblázat",
    plantSheetIdLabel       = "Növény adatok Sheet ID",
    plantSheetNameLabel     = "Növény adatok lap neve",
    nfcWriterUrlLabel       = "NFC lista író URL",
    nfcWriterSecretLabel    = "NFC lista titkos kulcs",
    saveSettings            = "Beállítások mentése",
    settingsSaved           = "Beállítások mentve ✓",
    reloadPlants            = "Növénylista újratöltése",
    resetDefaults           = "Alapértelmezések visszaállítása",
    nfcTypePlant            = "n – növény",
    nfcTypeGraft            = "o – oltás",
    nfcTypeSeed             = "m – mag",
    msgNfcWriteSuccess      = "NFC-re írva ✅",
    msgNfcWriteErrorPrefix  = "Írási hiba: ",
    msgSaved                = "Mentve!",
    msgSaveFailedPrefix     = "Mentés sikertelen: ",
    msgSelectPlantFirst     = "Először válassz növényt",
    msgGenerateFirst        = "Először generálj NFC adatokat",
    msgTapNfcTag            = "Érintsd az NFC jelölőt a telefonhoz…",
    msgLocationPermRequired = "GPS-hez helyzet engedély szükséges",
    msgCopied               = "Másolva!",
    msgSynced               = "Szinkronizálva!",
    msgImported             = "Importálva!",
    gpsReady                = "Kész.",
    gpsFetching             = "GPS műholdak keresése…",
    gpsUpdatingPrefix       = "Frissítés… (±",
    gpsLocked               = "Adatok rögzítve.",
    gpsNoFix                = "Még nincs vétel.",
    gpsPermDenied           = "GPS engedély megtagadva",
)

val LocalAppStrings = compositionLocalOf { englishStrings }
